#!/usr/bin/env bash
# script that prints comtemt according to the nth iteration
counter=1
while [ $counter -le 20 ]; do
	if [ $counter -eq 4 ]; then
		echo "bad luck from china"
	elif [ $counter -eq 8 ]; then
		echo "good luck from japan"
	elif [ $counter -eq 17 ]; then
		echo "bad luck from Italy"
	else
		echo "Best School"
	fi
	((counter++))
done
